In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


## Constant

In [2]:
TOKEN_SPAM_PROB_FILE = 'SPAM_DATA_MINE/02-Training/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'SPAM_DATA_MINE/02-Training/prob-ham.txt'
TOKEN_ALL_PROB_FILE = 'SPAM_DATA_MINE/02-Training/prob-all.txt'

TEST_FEATURE_MAT = 'SPAM_DATA_MINE/02-Training/test-feature.txt'
TEST_TARGET_FILE = 'SPAM_DATA_MINE/02-Training/test-target.txt'

VOCAB_SIZE = 2500


## Load the Data

In [4]:
X_test = np.loadtxt(TEST_FEATURE_MAT)
y_test = np.loadtxt(TEST_TARGET_FILE)

prob_tok_spam = np.loadtxt(TOKEN_SPAM_PROB_FILE)
prob_tok_ham = np.loadtxt(TOKEN_HAM_PROB_FILE)
prob_tok_all = np.loadtxt(TOKEN_ALL_PROB_FILE)



In [5]:
X_test[:5]

array([[0., 0., 1., ..., 0., 0., 0.],
       [6., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 2., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
X_test.shape

(1724, 2500)

In [7]:
prob_tok_spam.shape

(2500,)

$$P(SPAM | X) = \frac{P(X|SPAM)P(SPAM)}{P(X)}$$

In [8]:
PROB_SPAM = 0.3116 # As calculated earlier

In [9]:
np.log(prob_tok_spam)

array([-4.42143836, -5.26552594, -5.00053528, ..., -9.01609896,
       -8.88826559, -9.62223477])

## Joint Probability in LOG Format

In [10]:
joint_log_spam = X_test.dot(np.log(prob_tok_spam) - np.log(prob_tok_all)) + np.log(PROB_SPAM)

In [11]:
joint_log_spam[:5]

array([22.32399302,  1.9574354 , 17.79878103, 17.01330057, 19.50917501])

In [12]:
joint_log_ham = X_test.dot(np.log(prob_tok_ham) - np.log(prob_tok_all)) + np.log(1 - PROB_SPAM)

In [13]:
joint_log_ham[:5]

array([-58.92148191, -10.85050948, -34.74616051, -59.97564935,
       -53.06597974])

In [14]:
joint_log_ham.size

1724

## Making Predictions

In [15]:
prediction = joint_log_spam > joint_log_ham

In [18]:
prediction[-5:]*1

array([1, 0, 0, 0, 0])

In [19]:
y_test[-5:]

array([0., 0., 0., 0., 0.])

# Metrics and Evaluations

In [23]:
correct_docs = (y_test == prediction).sum()
print('Documents classified coorectly:',correct_docs)
wrong_docs = X_test.shape[0] - correct_docs
print('Documents classified in-correctly:',wrong_docs)

Documents classified coorectly: 1685
Documents classified in-correctly: 39


In [24]:
# Accuracy
correct_docs/len(X_test)

0.9773781902552204

## False Positive and False Negative

In [25]:
np.unique(prediction,return_counts=True)

(array([False,  True]), array([1138,  586], dtype=int64))

In [26]:
true_pos = (y_test ==1) & (prediction==1)

In [27]:
true_pos.sum()

568

In [28]:
false_pos = (y_test == 0) & (prediction ==1)

In [29]:
false_pos.sum()

18

In [30]:
false_neg = (y_test==1) & (prediction==0)
false_neg.sum()

21

## Recall Score

In [32]:
recall = true_pos.sum()/(true_pos.sum()+false_neg.sum())
print('Recall Score is {:.2%}'.format(recall))

Recall Score is 96.43%


## Precision

In [33]:
precision = true_pos.sum()/(true_pos.sum()+false_pos.sum())
print('Precision Score is {:.2%}'.format(precision))

Precision Score is 96.93%


## F Score or F-1 Score

In [35]:
F1_score = 2*(precision * recall)/(precision + recall)
print('F-1 Score is {:.2}'.format(F1_score))

F-1 Score is 0.97
